### ISSUE TITLE
Support Chinese characters in prompt generation stage

### ISSUE THREAD

**Issue by Tu-Zhenzhao** [Sinaptik-AI/pandas-ai#1168]
### System Info

pandasai == 2.0.43
python == 3.11

### 🐛 Describe the bug

I was trying to use *Field Descriptions* feature to improve the understanding of my dataset to LLMs. The way I am doing is write a data description function to create a dictionary info about dataset then pass then to pandasai through *Field Descriptions* like this:
```
data = preview_data(df)
# define a connector
connector = PandasConnector({"original_df": df}, name='My Connector', field_descriptions=data)
```
My part of `data` looks like this:
```
{'时间': 'The 时间 column contains string values. The unique values are: 2023-6-14, 2022-4-22, 2022-11-5.'}
```
As you can see there is some Chinese characters, but in the prompt_generation stage, the Chinese characters was not decoded thus it looks like this:
```
dfs[0]:
  name: My Connector
  description: null
  type: pd.DataFrame
  rows: 28
  columns: 18
  schema:
    fields:
    - name: "\u65F6\u95F4"
      type: object
      samples:
      - 2022-4-22
      - 2022-11-5
      - 2023-6-14
 ```
 Which makes LLM much more confused "\u65F6\u95F4". 
 
 Is any way we solve this problem? Any suggestion will be grateful!
