### ISSUE TITLE
The connector function cannot be used

### ISSUE THREAD

**Issue by MicoRobot** [sinaptik-ai/pandas-ai#1592]
### System Info

**OS version:** Ubuntu 22.04.4 LTS
**Python version:** Python 3.11.8
**PandasAI version:** 3.0.0b8

### 🐛 Describe the bug

I tried two different ways to install the connector. But none of them could be successfully imported.
`pip install pandasai[connectors]` and `pip install pandasai-bigquery`

Neither of the following two import methods can be used.
```
from pandasai.connectors import GoogleBigQueryConnector
from pandasai.ee.connectors.google_big_query import GoogleBigQueryConnector
```

Error msg:
```
Traceback (most recent call last):
  File "/home/wen/workspace/zhanghao/pandasAITest/test.py", line 8, in <module>
    from pandasai.connectors import GoogleBigQueryConnector
ModuleNotFoundError: No module named 'pandasai.connectors
```
```
Traceback (most recent call last):
  File "/home/wen/workspace/zhanghao/pandasAITest/test.py", line 9, in <module>
    from pandasai.ee.connectors.google_big_query import GoogleBigQueryConnector
ModuleNotFoundError: No module named 'pandasai.ee'
```

**Comment by gdcsinaptik** [comment]
Hey @MicoRobot have you installed the corresponding data package for the 3.0 (`pip install pandasai-bigquery)`?
You can find more info here: https://docs.getpanda.ai/v3/data-ingestion#how-to-work-with-enterprise-cloud-data-in-pandaai
Also, keep in mind that the Google BigQuery Connector falls under the "ee" code requiring a license. 
Here you can see which data extensions require a license and which do not: https://docs.getpanda.ai/v3/data-ingestion#all-data-extensions

**Comment by MicoRobot** [comment]
@gdcsinaptik thanks, and how should i use this config file? I don't see any instructions in the document on how to use it

**Comment by gdcsinaptik** [comment]
@MicoRobot you should create a schema in your dataset folder (https://docs.getpanda.ai/v3/semantic-layer/new#yaml-semantic-layer-configuration), then you can load the dataset, chat with It and even push to our data platform. Please take some time to read the updated documentation

**Comment by MicoRobot** [comment]
Sorry to ask again. but I tried `pai.create()` and `pai.load()`, but both got the same error. I think it might be a problem with the `source`, and I want to try modifying it, but I'm at a loss.

### **The code:**
```
import pandasai as pai
from pandasai_openai import OpenAI

openai_llm = OpenAI(
    api_token="openai_api_token",
)
pai.config.set({
    "llm": openai_llm,
})

def big_query(prompt):
    df = pai.create(
        path="test_com1/test-8g",
        source= {
            "type": "bigquery",
            "connection": {
                "project_id": "labeling-408016",
                "credentials": "~/workspace/zhanghao/pandasAITest/dev.json"
            },
            "table": "yt-agent"
        }
    )
    response = df.chat(prompt)
    return response


def load_yaml(prompt):
    df = pai.load("test_com/test-8g")
    response = df.chat(prompt)
    return response
```

### **The `test_com/test-8g/schema.yaml`**
```
name: inventory_data

source:
  type: bigquery
  connection:
    project_id: labeling-408016
    credentials: ~/workspace/zhanghao/pandasAITest/dev.json
  table: yt-agent

destination:
  type: local
  format: parquet
  path: company/bigquery-inventory

columns:
  - name: product_id
    type: string
    description: Unique identifier for each product
  - name: product_name
    type: string
    description: Name of the product
  - name: category
    type: string
    description: Product category
  - name: stock_level
    type: integer
    description: Current quantity in stock
  - name: last_updated
    type: datetime
    description: Last inventory update timestamp

transformations:
  - type: categorize
    params:
      column: stock_level
      bins: [0, 20, 100, 500]
      labels: ["Low", "Medium", "High"]
  - type: extract
    params:
      column: product_name
      pattern: "(.*?)\\s*-\\s*(.*)"
      into: [brand, model]
  - type: convert_timezone
    params:
      column: last_updated
      from: UTC
      to: Asia/Tokyo

update_frequency: hourly

order_by:
  - last_updated DESC

limit: 50000
```

### **`big_query()` and `load_yaml()` got the same error:**
```
Traceback (most recent call last):
  File "/home/wen/workspace/zhanghao/pandasAITest/test.py", line 94, in <module>
    print(load_yaml(prompt))
          ^^^^^^^^^^^^^^^^^
  File "/home/wen/workspace/zhanghao/pandasAITest/test.py", line 36, in load_yaml
    df = pai.load("test_com/test-8g")
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/wen/workspace/zhanghao/python/pandasAIVenvTest/lib/python3.11/site-packages/pandasai/__init__.py", line 234, in load
    loader = DatasetLoader.create_loader_from_path(dataset_path)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/wen/workspace/zhanghao/python/pandasAIVenvTest/lib/python3.11/site-packages/pandasai/data_loader/loader.py", line 51, in create_loader_from_path
    schema = cls._read_schema_file(dataset_path)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/wen/workspace/zhanghao/python/pandasAIVenvTest/lib/python3.11/site-packages/pandasai/data_loader/loader.py", line 66, in _read_schema_file
    return SemanticLayerSchema(**raw_schema)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/wen/workspace/zhanghao/python/pandasAIVenvTest/lib/python3.11/site-packages/pydantic/main.py", line 214, in __init__
    validated_self = self.__pydantic_validator__.validate_python(data, self_instance=self)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
pydantic_core._pydantic_core.ValidationError: 6 validation errors for SemanticLayerSchema
source.connection.host
  Field required [type=missing, input_value={'project_id': 'labeling-.../pandasAITest/dev.json'}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.10/v/missing
source.connection.port
  Field required [type=missing, input_value={'project_id': 'labeling-.../pandasAITest/dev.json'}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.10/v/missing
source.connection.database
  Field required [type=missing, input_value={'project_id': 'labeling-.../pandasAITest/dev.json'}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.10/v/missing
source.connection.user
  Field required [type=missing, input_value={'project_id': 'labeling-.../pandasAITest/dev.json'}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.10/v/missing
source.connection.password
  Field required [type=missing, input_value={'project_id': 'labeling-.../pandasAITest/dev.json'}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.10/v/missing
transformations.0.type
  Value error, Unsupported transformation type: categorize [type=value_error, input_value='categorize', input_type=str]
    For further information visit https://errors.pydantic.dev/2.10/v/value_error
```
